name: AEGEUS
version: dev
description: We need a boat.
depend: [GlowAPI]
authors: [VarusMain, Silvre]
main: com.aegeus.game.Aegeus

commands:
    # entity
    mob:
    openentity:
    hidespawners:
    showspawners:
    spawners:
      aliases: spawner

    # social
    global:
    message:
    party:
      aliases: p
    chatchannel:
    roll:

    # world
    addore:

    # item
    create: