name: AEGEUS
version: dev
description: We need a boat.
authors: [oopsjpeg, Silvre]
main: com.aegeus.game.Aegeus

commands:
    chatchannel:
      description: Changes your default chat channel.
      aliases: [cc, chat, channel]
      usage: /chatchannel <local / global>
    global:
      description: Send a message to all players on the server.
      aliases: gl
      usage: /global <message>
    message:
      description: Send a private message to a specified player.
      aliases: [msg, m, whisper, tell, pm]
      usage: /message <player> <message>
    roll:
      description: Roll a random number.
      usage: /roll [max number]
    spawner:
      description: Creates a spawner at the current location.
      usage: /spawner
    testarmor:
      description: Test armor.
    testenchant:
      description: Test enchants.
    testmob:
      description: Test entities.
    testweapon:
      description: Test weapons.
    testrod:
      description: Test fishing rods.