name: Aegeus
version: dev
description: We need a bigger boat.
authors: [oopsjpeg, Silvre]
main: com.aegeus.game.Aegeus

commands:
    # entity
    mob:
    openentity:

    # social
    global:
      aliases: gl
    message:
      aliases: m
    broadcast:
      aliases: bc

    # item
    create:
      aliases: cr
    generate:
      aliases: gen