name: AEGEUS
version: dev
description: We need a boat.
depend: [GlowAPI]
authors: [VarusMain, Silvre]
main: com.aegeus.game.Aegeus

commands:
    # entity
    mob:
    openentity:
    hidespawners:
    showspawners:
    spawner:
      aliases: spawners

    # social
    global:
      aliases: gl
    message:
      aliases: m
    party:
      aliases: p
    chatchannel:
      aliases: cc
    roll:
    broadcast:
      aliases: bc

    # world
    addore:

    # item
    create:
      aliases: cr
    generate:
      aliases: gen