name: AEGEUS
version: dev
description: We need a boat.
depend: [GlowAPI]
authors: [VarusMain, Silvre]
main: com.aegeus.game.Aegeus

commands:
    # entity
    mob:
    openentity:
    hidespawners:
    showspawners:
    spawner:
      aliases: spawners

    # social
    global:
    message:
    party:
    chatchannel:
    roll:

    # world
    addore:

    # item
    create:
    generate: